/*
 * Copyright (C) 2025 Smartsheet
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.smartsheet.api.models;

import com.smartsheet.api.models.enums.WebhookStatus;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

import java.util.Date;
import java.util.List;

/**
 * Represents a Webhook object.
 */
@Data
@NoArgsConstructor
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = true)
public class Webhook extends NamedModel<Long> {

    /**
     * API Client ID corresponding to third-party app that created the Webhook.
     */
    private String apiClientId;

    /**
     * ID of the object that is subscribed to.
     */
    private Long scopeObjectId;

    /**
     * API Client Name corresponding to third-party app that created the Webhook.
     */
    private String apiClientName;

    /**
     * HTTPS URL where callbacks will be sent.
     */
    private String callbackUrl;

    /**
     * Time of creation
     */
    private Date createdAt;

    /**
     * Details about the reason the Webhook is disabled.
     */
    private String disabledDetails;

    /**
     * Flag indicating whether the Webhook is on (true) or off (false).
     */
    private Boolean enabled;

    /**
     * Array of events that are subscribed to.
     */
    private List<String> events;

    /**
     * Time of last modification
     */
    private Date modifiedAt;

    /**
     * Scope of the subscription.
     */
    private String scope;

    /**
     * Shared secret for this webhook, randomly generated by Smartsheet.
     */
    private String sharedSecret;

    /**
     * Useful statistics for this webhook.
     */
    private WebhookStats stats;

    /**
     * Webhook status.
     */
    private WebhookStatus status;

    /**
     * Array of columnIds if you want to limit the subscription to a subscope.
     * Specified when a webhook is created and cannot be changed.
     */
    private WebhookSubscope subscope;

    /**
     * Webhook version.
     */
    private Integer version;

    /**
     * Get flag indicating whether the webhook is on(true) or off(false)
     *
     * @return enabled
     */
    public Boolean isEnabled() {
        return enabled;
    }
    
    /**
     * Builder for creating Webhook instances
     */
    public static class WebhookBuilder {
        private Long id;
        private String name;
        private String apiClientId;
        private Long scopeObjectId;
        private String apiClientName;
        private String callbackUrl;
        private Date createdAt;
        private String disabledDetails;
        private Boolean enabled;
        private List<String> events;
        private Date modifiedAt;
        private String scope;
        private String sharedSecret;
        private WebhookStats stats;
        private WebhookStatus status;
        private WebhookSubscope subscope;
        private Integer version;
        
        public WebhookBuilder id(Long id) {
            this.id = id;
            return this;
        }
        
        public WebhookBuilder name(String name) {
            this.name = name;
            return this;
        }
        
        public WebhookBuilder apiClientId(String apiClientId) {
            this.apiClientId = apiClientId;
            return this;
        }
        
        public WebhookBuilder scopeObjectId(Long scopeObjectId) {
            this.scopeObjectId = scopeObjectId;
            return this;
        }
        
        public WebhookBuilder apiClientName(String apiClientName) {
            this.apiClientName = apiClientName;
            return this;
        }
        
        public WebhookBuilder callbackUrl(String callbackUrl) {
            this.callbackUrl = callbackUrl;
            return this;
        }
        
        public WebhookBuilder createdAt(Date createdAt) {
            this.createdAt = createdAt;
            return this;
        }
        
        public WebhookBuilder disabledDetails(String disabledDetails) {
            this.disabledDetails = disabledDetails;
            return this;
        }
        
        public WebhookBuilder enabled(Boolean enabled) {
            this.enabled = enabled;
            return this;
        }
        
        public WebhookBuilder events(List<String> events) {
            this.events = events;
            return this;
        }
        
        public WebhookBuilder modifiedAt(Date modifiedAt) {
            this.modifiedAt = modifiedAt;
            return this;
        }
        
        public WebhookBuilder scope(String scope) {
            this.scope = scope;
            return this;
        }
        
        public WebhookBuilder sharedSecret(String sharedSecret) {
            this.sharedSecret = sharedSecret;
            return this;
        }
        
        public WebhookBuilder stats(WebhookStats stats) {
            this.stats = stats;
            return this;
        }
        
        public WebhookBuilder status(WebhookStatus status) {
            this.status = status;
            return this;
        }
        
        public WebhookBuilder subscope(WebhookSubscope subscope) {
            this.subscope = subscope;
            return this;
        }
        
        public WebhookBuilder version(Integer version) {
            this.version = version;
            return this;
        }
        
        public Webhook build() {
            Webhook webhook = new Webhook();
            webhook.setId(id);
            webhook.setName(name);
            webhook.apiClientId = apiClientId;
            webhook.scopeObjectId = scopeObjectId;
            webhook.apiClientName = apiClientName;
            webhook.callbackUrl = callbackUrl;
            webhook.createdAt = createdAt;
            webhook.disabledDetails = disabledDetails;
            webhook.enabled = enabled;
            webhook.events = events;
            webhook.modifiedAt = modifiedAt;
            webhook.scope = scope;
            webhook.sharedSecret = sharedSecret;
            webhook.stats = stats;
            webhook.status = status;
            webhook.subscope = subscope;
            webhook.version = version;
            return webhook;
        }
    }
    
    /**
     * Creates a new builder for Webhook
     *
     * @return a new WebhookBuilder
     */
    public static WebhookBuilder builder() {
        return new WebhookBuilder();
    }
}
