name: Test PR

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run Unit Tests
        env:
          SMARTSHEET_ACCESS_TOKEN: ${{secrets.SMARTSHEET_ACCESS_TOKEN}}
        run: ./gradlew clean build jacocoTestReport

  integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Check Smartsheet Access Token Presence
        id: checksecrets
        shell: bash
        run: |
          if [ "SMARTSHEET_ACCESS_TOKEN" == "" ]; then
            echo "hasAccessToSmartsheetAccessToken=NO" >> $GITHUB_OUTPUT
          else
            echo "hasAccessToSmartsheetAccessToken=YES" >> $GITHUB_OUTPUT
          fi
        env:
          SMARTSHEET_ACCESS_TOKEN: ${{ secrets.SMARTSHEET_ACCESS_TOKEN}}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run Integration Tests
        if: (steps.checksecrets.outputs.hasAccessToSmartsheetAccessToken == 'YES')
        env:
          SMARTSHEET_ACCESS_TOKEN: ${{secrets.SMARTSHEET_ACCESS_TOKEN}}
        run: ./gradlew clean integrationTest

  shared-mock-api-sdk-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Clone smartsheet/smartsheet-sdk-tests PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'smartsheet'
          repository: 'smartsheet-sdk-tests'
      - name: Setup Mock API
        run: |
          smartsheet-sdk-tests/ci_scripts/install_wiremock.sh
          smartsheet-sdk-tests/ci_scripts/start_wiremock.sh
      - name: Run Mock API SDK Tests
        run: ./gradlew clean sdkTest
